local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/uilib.lua", true))()

local tab1 = library:CreateTab("Bypasses", true)
local button = library:MakeButton(tab1,"Main",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab1,"Teleport",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab1,"Noclip",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab1,"Walkspeed",function(button)
   print ("Hi")
end)

local tab2 = library:CreateTab("Utility", true)
local button = library:MakeButton(tab2,"Inf Stamina",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab2,"Name Hider",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab2,"AutoPickUp",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab2,"OPshotgun",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab2,"NoDelay",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab2,"AntiCar",function(button)
   print ("Hi")
end)
local tab3 = library:CreateTab("Farm", true)
local button = library:MakeButton(tab3,"Printers",function(button)
   print ("Hi")
end)
local button = library:MakeButton(tab3,"UnlockedPrinters",function(button)
   print ("Hi")
end)
