-- Put all together by Raisaga#4491
-- Scripts from Shariiii
-- UI LIB by Insane#7688
local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/uilib.lua", true))()

local tab1 = library:CreateTab("Bypasses", true)
local button = library:MakeButton(tab1,"Main",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Main%20Bypass.lua", true))()
end)
local button = library:MakeButton(tab1,"Teleport",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Teleport%20Bypass.lua", true))()
end)
local button = library:MakeButton(tab1,"Noclip",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Noclip%20Bypass.lua", true))()
end)
local button = library:MakeButton(tab1,"Walkspeed",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/walkspeed%20bypass.lua", true))()
end)

local tab2 = library:CreateTab("Utility", true)
local button = library:MakeButton(tab2,"Inf Stamina",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Inf%20Stamina.lua", true))()
end)
local button = library:MakeButton(tab2,"Name Hider",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Name%20Hider.lua", true))()
end)
local button = library:MakeButton(tab2,"AutoPickUp",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/auto%20of%20my%20og%20pickup%20script.lua", true))()
end)
local button = library:MakeButton(tab2,"OPshotgun",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/OPshotgun.lua", true))()
end)
local button = library:MakeButton(tab2,"NoDelay",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/NoDelay.lua", true))()
end)
local button = library:MakeButton(tab2,"AntiCar",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/Anti%20Car%20Damage.lua", true))()
end)
local tab3 = library:CreateTab("Farm", true)
local button = library:MakeButton(tab3,"Printers",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/printer%20farm.lua", true))()
end)
local button = library:MakeButton(tab3,"UnlockedPrinters",function(button)
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Raisaga/anomicgui/main/unlocked%20printer%20farm.lua", true))()
end)
